### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by Popolon** [michg/elftools_riscv32#1]
On all (or most) non-Microsoft (DOS or Windows) systems, file names are case sensitive.

So, when compiling minas:
<pre>
c99 -O1 -D _GNU_SOURCE   -c -o main.o main.c
In file included from main.c:1:
minias.h:16:12: fatal error: riscv.def: No such file or directory
   16 |   #include "riscv.def"
</pre>

And the file is currently called RISCV.def

After changing it in minias/minias.h and neatld/nld.c to RISCV.def, there is still error:

<pre>
c99 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Wno-error=format-security         -fstack-clash-protection -fcf-protection -D _GNU_SOURCE   -c -o tree.o tree.c
Dans le fichier inclus depuis main.c:1:
RISCV.def:6:11: erreur: expected identifier before numeric constant
    6 | ELF_RELOC(R_RISCV_NONE,               0)
</pre>

**Comment by michg** [comment]
Changed, thanks.

**Comment by Popolon** [comment]
But as said, it still fails to build :), R_RISCV_NONE, isn't defined.

<pre>
c99 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Wno-error=format-security         -fstack-clash-protection -fcf-protection -D _GNU_SOURCE   -c -o tree.o tree.c
Dans le fichier inclus depuis main.c:1:
RISCV.def:6:11: erreur: expected identifier before numeric constant
    6 | ELF_RELOC(R_RISCV_NONE,               0)
</pre>

**Comment by michg** [comment]
It is necessary, that the compiler runs the preprocessor for minias.h. This then expands to this enum:
# 15 "minias.h"
enum {
# 1 "RISCV.def" 1
R_RISCV_NONE = 0,
R_RISCV_32 = 1,
R_RISCV_64 = 2,
R_RISCV_RELATIVE = 3,
